name: Deploy docs


on: 
  workflow_dispatch:
  push:
      branches: [master,versions] # TODO: remove branch versions 
      tags:
        - '*'

jobs:
  evaluate-label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.label_step.outputs.version}}
    steps:
      - name: checks for the label 
        id: label_step 
        run: |
          if [[ "${{ github.ref  }}" == "refs/heads/versions" ]]; then # TODO: modify the branch after merging
                echo "version=latest" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.ref_type }}" == "branch" ]] && [[ "${{ github.ref  }}" != "refs/heads/versions" ]]; then # TODO: modify the branch after merging
                exit 1
          fi
          if [[ "${{ github.ref_type }}" == "tag" ]]; then 
                echo "version=stable" >> $GITHUB_OUTPUT
          fi 

  deploy-docs:
    needs: [evaluate-label]
    uses: qibogang/workflows/.github/workflows/deploy-ghpages-latest-stable.yml@tar
    with:
      python-version: 3.9
      package-manager: 'pip'
      dependency-path: '**/setup.py'
      trigger-label: '${{needs.evaluate-label.outputs.label}}'

