# A single CI script with github workflow
name: Pip upload

on:
  release:
    types: [created]

env:
  TEST_CUDA_PATH: /usr/local/cuda-10.1/

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6,3.7,3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install CUDA on ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
        sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda-10.1
    - name: Install python package requirements
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt
    - name: Build and publish
      run: |
        # check if CUDA is installed
        [ -d $TEST_CUDA_PATH ] && export CUDA_PATH=$TEST_CUDA_PATH
        # build wheels
        python setup.py sdist bdist_wheel
        # twine upload dist/*
    - name: Upload to server
      run: |
        KEY=$( mktemp )
        echo "$QIBO_TEAM" | base64 --decode > "$KEY"
        scp -r -i "$KEY" -o StrictHostKeyChecking=no\
          dist/* \
          ubuntu@34.240.99.72:/var/www/html/packages/
      env:
        QIBO_TEAM: ${{ secrets.QIBO_TEAM }}