# A single CI script with github workflow
name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set numba version for macos
      if: startsWith(matrix.os, 'macos')
      run: |
        python -m pip install --upgrade pip
        pip install numba==0.53.1
    - name: Install package
      if: startsWith(matrix.os, 'windows') == 0
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install .[tests,docs]
        pip install qibotf --pre
        pip install qibojit --pre
    - name: Install package on Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install qibojit --pre
        pip install .[tests,docs]
    - name: Test with pylint
      run: |
        pip install pylint
        pylint src -E -d E1123,E1120
    - name: Test with pytest core
      run: |
        pytest --cov=qibo --cov-report=xml --pyargs qibo
    - name: Test documentation examples
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install pandoc
        make -C doc doctest
    - name: Test examples
      if: startsWith(matrix.os, 'ubuntu') && matrix.python-version == '3.9'
      run: |
        OMP_NUM_THREADS=1 pytest examples/
    - name: Upload coverage to Codecov
      if: startsWith(matrix.os, 'ubuntu')
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
