# CI workflow that runs on selfhosted GPU
name: Tests with gpu

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: contains(join(github.event.pull_request.labels.*.name), 'run-on')
    uses: qiboteam/workflows/.github/workflows/selfhosted.yml@selfhosted
    with:
      used-labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      python-version: "3.10"
      repository-url: ${{ github.server-url }}/${{ github.repository }}
      run-id: ${{ github.run-id }}
      poetry-extras: "--with cuda11,tests"

    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
